### ISSUE TITLE
[Perlin] Интерполяция

### ISSUE THREAD

**Issue by pavel-b-novikov** [alex-ks/nsudotnet#1]
Пожалуйста ознакомьтесь: https://ru.wikipedia.org/wiki/Бикубическая_интерполяция

с вон той большой и толстой матрицей и сделайте интерполяцию с помощью неё.

**Comment by alex-ks** [comment]
Именно она и используется в последнем коммите.

**Comment by pavel-b-novikov** [comment]
А теперь подсчитайте сколько раз у вас создается новый экземпляр этого массива.

**Comment by alex-ks** [comment]
Исправлено
