### ISSUE TITLE
[TaskScheduler] ThreadPool

### ISSUE THREAD

**Issue by pavel-b-novikov** [alex-ks/nsudotnet#3]
Заценил я ваш кастомный тредпул. Весьма странная конструкция, конечно.

Во-первых. У нас есть нестатичный сам по себе тред-пул, который можно инстанциировать в любой момент и грохнуть, наверное тоже. А вот счетчик тредов в нем статический! Бинго! А нет, погодите.. счетчик тредов статический, но лежит в каждом треде! Тысяча чертей, какая архитектура!

Во-вторых:

``` C#
try
{
 lock ( this )
 {
  Monitor.Wait( this );
 }
}
```

Я полчаса силился понять, что делает эта конструкция, но так и не въехал. Александр, утоли моя печали.

В-третьих:
Сначала он говорит тебе: "Я пишу Thread Pool". Но потом...

``` C#
thread = new Thread( this.Execute );
```

Штоза?... Смысл-то пула тредов в чем?

В-четвертых:

``` C#
default( PooledThread )
```

Я вот категорически не понимаю чем вам так нравится оператор default, что вы используете его везде и всея. Зачем он вам? Может стоит остановиться? Впрочем, это не критично.

**Comment by alex-ks** [comment]
Статический счетчик - наследие тяжких времен, когда сам тредпул был статическим. Поправил.

Смысл конструкции с Wait в том, что когда поток завершает выполнение задачи, он переводит себя в множество неактивных потоков и засыпает на на объекте PooledThread, который, по сути, является хэндлом к потоку. При поступлении же новой задачи тредпул достанет его из неактивных, положит в очередь новую задачу и разбудит с помощью Pulse. Такая схема применена потому, что TryDequeue не является блокирующимся. Кроме того, считается, что после выполнения задачи в очереди ничего нового не появилось, т. к. новые задачи поступают только неактивным потокам.

Суть же всей данной конструкции в том мы создаем не заданное изначально количество потоков сразу, а по одному и только при необходимости. При этом, выполневшие работу потоки не завершаются, а засыпают на своих хэндлах, чтобы трэдпул при поступлении новой задачи разбудил какого-то из них и вручил задачу ему. Такая схема была выбрана потому, что пул с постоянным количеством потоков может оказаться полностью забитым периодическими задачами, и никакую новую запустить будет нельзя.

Оператор default был использован потому, что ConcurrentDictionaty.TryRemove складывает в value дефолтное значение, если в нем нет пары с указанным ключом. В остальных же случаях это действительно излишне.

**Comment by pavel-b-novikov** [comment]
Ну на будущее: тред-пул как раз и нужен, чтобы ЗАРАНЕЕ выделить определенное кол-во тредов и не тратить время на это при запуске приложения. Это раз.
Два. Кто вам сказал что встроенные ThreadPool работает по-другому? 
Три - так и что все-таки делает оператор default?

**Comment by alex-ks** [comment]
Для ссылочных типов возвращает null, для value - объект, созданный конструктором без параметров.

**Comment by pavel-b-novikov** [comment]
> ConcurrentDictionaty.TryRemove складывает в value дефолтное значение
> Ну то есть тот же самый null.

Default надо использовать когда вы работате с generic-ами и дополдлинно не знаете какого T типа - ref или val.
